graph TD
    b003d2b1_223c_4979_9b30_88a9628e4f62__LayeredSample_Infrastructure_Data[LayeredSample.Infrastructure.Data]
    b8911d71_a4f9_4d05_a8cb_0fe0235ebbe3__LayeredSample_Api_Endpoints[LayeredSample.Api.Endpoints]
    c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Abstractions[LayeredSample.Application.Abstractions]
    c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Invoices[LayeredSample.Application.Invoices]
    e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Orders[LayeredSample.Domain.Orders]
    e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Policies[LayeredSample.Domain.Policies]
    b003d2b1_223c_4979_9b30_88a9628e4f62__LayeredSample_Infrastructure_Data --> c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Abstractions
    b003d2b1_223c_4979_9b30_88a9628e4f62__LayeredSample_Infrastructure_Data --> e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Orders
    b8911d71_a4f9_4d05_a8cb_0fe0235ebbe3__LayeredSample_Api_Endpoints --> c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Invoices
    c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Abstractions --> e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Orders
    c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Invoices --> c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Abstractions
    c48bd50a_18fc_4f77_b41f_bc87c35fe9da__LayeredSample_Application_Invoices --> e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Policies
    e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Orders --> e5bd3090_c7f1_4dc6_859e_5a9c0a24b614__LayeredSample_Domain_Policies