graph TD
    project__LayeredSample_Api__namespace__LayeredSample_Api_Endpoints[LayeredSample.Api.Endpoints]
    project__LayeredSample_Application__namespace__LayeredSample_Application_Abstractions[LayeredSample.Application.Abstractions]
    project__LayeredSample_Application__namespace__LayeredSample_Application_Invoices[LayeredSample.Application.Invoices]
    project__LayeredSample_Domain__namespace__LayeredSample_Domain_Orders[LayeredSample.Domain.Orders]
    project__LayeredSample_Domain__namespace__LayeredSample_Domain_Policies[LayeredSample.Domain.Policies]
    project__LayeredSample_Infrastructure__namespace__LayeredSample_Infrastructure_Data[LayeredSample.Infrastructure.Data]
    project__LayeredSample_Api__namespace__LayeredSample_Api_Endpoints --> project__LayeredSample_Application__namespace__LayeredSample_Application_Invoices
    project__LayeredSample_Application__namespace__LayeredSample_Application_Abstractions --> project__LayeredSample_Domain__namespace__LayeredSample_Domain_Orders
    project__LayeredSample_Application__namespace__LayeredSample_Application_Invoices --> project__LayeredSample_Application__namespace__LayeredSample_Application_Abstractions
    project__LayeredSample_Application__namespace__LayeredSample_Application_Invoices --> project__LayeredSample_Domain__namespace__LayeredSample_Domain_Policies
    project__LayeredSample_Domain__namespace__LayeredSample_Domain_Orders --> project__LayeredSample_Domain__namespace__LayeredSample_Domain_Policies
    project__LayeredSample_Infrastructure__namespace__LayeredSample_Infrastructure_Data --> project__LayeredSample_Application__namespace__LayeredSample_Application_Abstractions
    project__LayeredSample_Infrastructure__namespace__LayeredSample_Infrastructure_Data --> project__LayeredSample_Domain__namespace__LayeredSample_Domain_Orders